-- ====================================================================================
-- CẤU TRÚC DATABASE SUPABASE (POSTGRESQL + POSTGIS)
-- Copy toàn bộ nội dung file này và paste vào SQL Editor trên Supabase để chạy.
-- ====================================================================================

-- Bật tính năng Bản đồ (PostGIS)
CREATE EXTENSION IF NOT EXISTS postgis;

-- ------------------------------------------------------------------------------------
-- 1. BẢNG TRẠM SẠC XE ĐIỆN (EV STATIONS)
-- ------------------------------------------------------------------------------------
-- 1. BẢNG TRẠM SẠC XE ĐIỆN (EV STATIONS)
-- ------------------------------------------------------------------------------------
DROP TABLE IF EXISTS ev_stations CASCADE;
CREATE TABLE ev_stations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    provider VARCHAR(100), -- Ví dụ: VinFast, ChargeAlong, EVOne
    address TEXT,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    capacity INT DEFAULT 1, -- Số cổng sạc
    is_active BOOLEAN DEFAULT true,
    location GEOGRAPHY(Point, 4326) -- Tọa độ chuẩn hệ quy chiếu toàn cầu
);

-- Tự động tính toán cột 'location' dựa vào 'lat' và 'lng'
CREATE OR REPLACE FUNCTION update_ev_location()
RETURNS TRIGGER AS $$
BEGIN
  NEW.location = ST_SetSRID(ST_MakePoint(NEW.lng, NEW.lat), 4326);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_ev_location
BEFORE INSERT OR UPDATE ON ev_stations
FOR EACH ROW EXECUTE FUNCTION update_ev_location();

-- Thêm một vài dữ liệu mẫu ở Hà Nội để test Giao diện
INSERT INTO ev_stations (name, provider, address, lat, lng) VALUES
('Trạm sạc Vincom Metropolis', 'VinFast', '29 Liễu Giai, Ba Đình', 21.0319, 105.8115),
('Trạm sạc Vincom Trần Duy Hưng', 'VinFast', '119 Trần Duy Hưng, Cầu Giấy', 21.0069, 105.7951),
('Trạm sạc Royal City', 'VinFast', '72A Nguyễn Trãi, Thanh Xuân', 21.0028, 105.8155),
('Tủ thay pin Selex Motors', 'Selex', 'Đại học Bách Khoa Hà Nội', 21.0041, 105.8437);


-- ------------------------------------------------------------------------------------
-- 2. BẢNG LƯU TRỮ LỊCH SỬ GIAO THÔNG (Lưu 7 ngày)
-- ------------------------------------------------------------------------------------
-- 2. BẢNG LƯU TRỮ LỊCH SỬ GIAO THÔNG (Lưu 7 ngày)
-- ------------------------------------------------------------------------------------
DROP TABLE IF EXISTS traffic_history CASCADE;
CREATE TABLE traffic_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment_id VARCHAR(100) NOT NULL, -- Mã của đoạn đường
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    speed_kmh INT,
    congestion_level INT CHECK (congestion_level >= 0 AND congestion_level <= 5),
    weather_condition VARCHAR(50) -- Ví dụ: sunny, raining
);

-- Tạo Index để tìm kiếm tốc độ siêu nhanh theo thời gian
CREATE INDEX idx_traffic_history_time ON traffic_history(recorded_at);


-- ------------------------------------------------------------------------------------
-- 3. BẢNG DỮ LIỆU DỰ BÁO TƯƠNG LAI (AI XGBOOST GHI VÀO ĐÂY)
-- ------------------------------------------------------------------------------------
-- 3. BẢNG DỮ LIỆU DỰ BÁO TƯƠNG LAI (AI XGBOOST GHI VÀO ĐÂY)
-- ------------------------------------------------------------------------------------
DROP TABLE IF EXISTS traffic_predictions CASCADE;
CREATE TABLE traffic_predictions (
    segment_id VARCHAR(100) NOT NULL,
    target_hour INT NOT NULL, -- Giá trị: 1 (1h tới), 2 (2h tới), 3 (3h tới)
    predicted_level INT, -- Mức kẹt xe dự đoán (0-5)
    confidence FLOAT, -- Độ tự tin của AI (0.0 - 1.0)
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (segment_id, target_hour)
);

-- ====================================================================================
-- RLS (Row Level Security) - Bảo mật Database
-- ====================================================================================
-- Cho phép mọi người (Client/Frontend) đọc dữ liệu trạm sạc và dự báo (để vẽ bản đồ)
ALTER TABLE ev_stations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read EV Stations" ON ev_stations FOR SELECT USING (true);

ALTER TABLE traffic_predictions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Predictions" ON traffic_predictions FOR SELECT USING (true);

-- Backend (AI Bot) sẽ dùng Service Key có toàn quyền để ghi dữ liệu lịch sử vào.
-- ------------------------------------------------------------------------------------
-- 4. BẢNG DỮ LIỆU DỰ BÁO NGẬP LỤT (AI DỰ ĐOÁN)
-- ------------------------------------------------------------------------------------
DROP TABLE IF EXISTS flood_predictions CASCADE;
CREATE TABLE flood_predictions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    location_name VARCHAR(255) NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    target_hour INT NOT NULL,
    predicted_depth_cm INT,
    confidence DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
